### ISSUE TITLE
Matched from path parameters overrides values passed via query string

### ISSUE THREAD

**Issue by kaero** [nodules/susanin#29]
Route definition:
```javascript
{
    pattern: '/jeans(/<brand>(/<id>))',
    conditions: {
        brand: [ 'levis', 'wrangler' ],
        id: '\\d{3,5}'
    },
    defaults: {
        brand: 'levis'
    }
}
```

Result for URL `'/jeans/levis?id=567&id=678'`:
```javascript
{
    "brand": "levis",
    "id": [ "567", "678" ]
}
```
but result for URL `'/jeans/levis/456?id=567&id=678'` looks incorrect (query string values overridden by matched from path, instead of be extended):
```javascript
{
    "brand": "levis",
    "id": "456"
}
```

**Comment by ruslankerimov** [comment]
We told with @kaero about logic of merging params and it had already been fixed in *1.0.0* version: [demo1](http://nodul.es/susanin/#%7B%0A%20%20%20%20pattern%3A%20'%2Fjeans(%2F%3Cbrand%3E(%2F%3Cid%3E))'%2C%0A%20%20%20%20conditions%3A%20%7B%0A%20%20%20%20%20%20%20%20brand%3A%20%5B%20'levis'%2C%20'wrangler'%20%5D%2C%0A%20%20%20%20%20%20%20%20id%3A%20'%5C%5Cd%7B3%2C5%7D'%0A%20%20%20%20%7D%0A%7D%3A%3A'%2Fjeans%2Flevis%3Fid%3D123%26id%3D567'%3A%3A%3A%3A1.0.0%3A%3A%3A%3Afalse), [demo2](http://nodul.es/susanin/#%7B%0A%20%20%20%20pattern%3A%20'%2Fjeans(%2F%3Cbrand%3E(%2F%3Cid%3E))'%2C%0A%20%20%20%20conditions%3A%20%7B%0A%20%20%20%20%20%20%20%20brand%3A%20%5B%20'levis'%2C%20'wrangler'%20%5D%2C%0A%20%20%20%20%20%20%20%20id%3A%20'%5C%5Cd%7B3%2C5%7D'%0A%20%20%20%20%7D%0A%7D%3A%3A'%2Fjeans%2Flevis%3Fid%3D123%26id%3D567'%3A%3A%3A%3A1.0.0%3A%3A%3A%3Afalse).
